version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
  web:
    build: .
    container_name: rails_app
    command: ["./entrypoint.sh", "bundle" , "exec", "rails", "s", "-b", "0.0.0.0"]
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
      # DB_HOST: host.docker.internal
      SECRET_KEY_BASE: ad874bcfc729d2cf9d7e03c8b9b7a8c7e9796949d5f04acaac5105c03bf08dc80eae622267914a7e62c3c6c5bd715fc5fa78f41e6e61b28b7dbc72be412a2536
volumes:
  postgres_data:
