default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["HOA_DATABASE_USERNAME"] %>
  password: <%= ENV["HOA_DATABASE_PASSWORD"] %>
  database: <%= ENV["HOA_DATABASE_NAME"] %>
  host: <%= ENV["HOA_DATABASE_HOST"] %>


development:
  <<: *default

staging:
  <<: *default
  
test:
  <<: *default

production:
  <<: *default